FROM node:18.16.0

WORKDIR /app
COPY ./api/package.json .
RUN npm install

COPY ./api .

ARG NODE_ENV

RUN echo "NODE_ENV: $NODE_ENV"

RUN if [ "$NODE_ENV" = "production" ] ; then npm run build ; fi
CMD if [ "$NODE_ENV" = "production" ] ; then npm start ; else npm run dev ; fi